# This file contains configuration options (e.g. algorithm parameters' values) for the optimal filter algorithm.

data:
  inputPath: resources/images/article.png
  outputPath: resources/results/optimal_filter_article_1.png
  thinnedOutputPath: resources/results/optimal_filter_article_thinned_1.png
  logsOutputPath: logs/optimal_filter_article_1.log

algorithm:
  probability:
    crossover: 0.8
    mutation: 0.2
    class: Default

  initializer:
    initialSize: 11                        # Must be an odd number because of using the elitism strategy.
    class: RandomUniformInitializer

  crossover:
    class: RandomMultipleGenesCrossover

  mutation:
    class: RandomGaussianMutation

  threshold:
    class: OtsuThresholding

  fitness:
    powerCoefficient: 1.0

  cost:
    targetDeviation: 0.28

  selection:
    class: RouletteWheelSelection
    repetition: True

  stopCondition:
    class: FitnessOrMaxStepsStopCondition
    desiredFitness: 0.0
    fitnessTolerance: 0.005
    maxSteps: 100
