# This file contains configuration options (e.g. algorithm parameters' values).

data:
  inputPath: resources/data/input/test.jpg
  outputPath: resources/data/output/test_result.jpg

algorithm:
  initialPopulationSize: 512
  mutationProbability: 0.008
  crossoverProbability: 0.6
