# This file contains configuration options (e.g. algorithm parameters' values) for the edge improvement algorithm.

data:
  inputPath: resources/images/megan_small.png
  outputPath: resources/results/megan_small.png

algorithm:

  initializer:
    initialSize: 5                 # Must be an odd number because of using the elitism strategy.
    threshold: 0.1
    similarityToReference: 0.5
    class: RandomInitializer

  crossover:
    probability: 0.6
    rowSiteRange: 3
    columnSiteRange: 3
    class: RandomCrossover

  mutation:
    probability: 0.008
    # neighboursMin: 2
    # class: RandomMutation
    class: IntelligentMutation


  fitness:
    powerCoefficient: 2.0

  cost:
    weights:
      curvature: 1.0
      fragmentation: 1.0
      dissimilarity: 1.0
      edge: 1.0
      thickness: 1.0

  selection:
    class: RouletteWheelSelection
    repetition: True

  stopCondition:
    class: StepsNumberStopCondition
    maxSteps: 1
