# This file contains configuration options (e.g. algorithm parameters' values).

data:
  inputPath: resources/images/megan_small.png
  outputPath: resources/results/megan_small.png

algorithm:

  initializer:
    initialSize: 5
    class: RandomInitializer

  crossover:
    probability: 0.6
    class: RandomCrossover

  mutation:
    probability: 0.008
    class: RandomMutation

  fitness:
    powerCoefficient: 2.0

  cost:
    weights:
      curvature: 1.0
      fragmentation: 1.0
      dissimilarity: 1.0
      edge: 1.0
      thickness: 1.0

  selection:
    class: RouletteWheelSelection
    repetition: False

  stopCondition:
    class: StepsNumberStopCondition
    maxSteps: 1
